### ISSUE TITLE
Error in projects settings

### ISSUE THREAD

**Issue by Oskaria** [suer/redmine_webhook#25]
After install the plugin - "Settings" page, from projects, do not open with errors:

`Started GET "/projects/bcd/settings" for 80.243.11.22 at 2019-07-03 18:26:25 +0300
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"bcd"}
  Current user: admin (id=1)
  Rendered projects/settings.html.erb within layouts/base (208.1ms)
Completed 500 Internal Server Error in 224ms (ActiveRecord: 2.1ms)

ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x00007ff2b3b13048>:0x00007ff2b3ace9c0>
Did you mean?  project_settings_tabs_with_contacts):
    1: <h2><%=l(:label_settings)%></h2>
    2:
    3: <%= render_tabs project_settings_tabs %>
    4:
    5: <% html_title(l(:label_settings)) -%>
  plugins/redmine_webhook/lib/redmine_webhook/projects_helper_patch.rb:4:in `project_settings_tabs'
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/projects_helper_patch.rb:11:in `project_settings_tabs_with_hourglass'
  plugins/redmine_webhook/lib/redmine_webhook/projects_helper_patch.rb:4:in `project_settings_tabs'
  app/views/projects/settings.html.erb:3:in `_e9ef3e01a08edaad94e3139658a0865e'
`

I rename project_settings_tabs function from webhook_settings_controller.rb, but now webhooks setting dont show on project settings page.

What I can do with it?)

**Comment by Oskaria** [comment]
redmine version id 3.4

**Comment by suer** [comment]
current master of this plugin requires Redmine 4.0 or later.

Please update Redmine or use older revision than c1227619392cb3c9db3709f6dda681609592cae3.

**Comment by Oskaria** [comment]
Some error:

`Started GET "/projects/bcd/settings" for 80.243.11.22 at 2019-07-05 15:14:47 +0300
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"bcd"}
  Current user: admin (id=1)
  Rendered projects/settings.html.erb within layouts/base (294.0ms)
Completed 500 Internal Server Error in 308ms (ActiveRecord: 2.0ms)

ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x0000556d2dccd540>:0x00007fab03efa550>
Did you mean?  project_settings_tabs_with_contacts):
    1: <h2><%=l(:label_settings)%></h2>
    2:
    3: <%= render_tabs project_settings_tabs %>
    4:
    5: <% html_title(l(:label_settings)) -%>
  plugins/redmine_webhook/lib/redmine_webhook/projects_helper_patch.rb:4:in `project_settings_tabs'
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/projects_helper_patch.rb:11:in `project_settings_tabs_with_hourglass'
  plugins/redmine_webhook/lib/redmine_webhook/projects_helper_patch.rb:4:in `project_settings_tabs'
  app/views/projects/settings.html.erb:3:in `_f30839a8baebffa9039069c95acc8e9c'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
`

and rename of function doesn`t have effect((
