### ISSUE TITLE
Circular dependency detected while autoloading constant RedmineWebhook

### ISSUE THREAD

**Issue by jegade** [suer/redmine_webhook#6]
After upgrading to latest redmine/svn and rails this error message appers - if i remove the Plugin, anything works as expected:

<pre>
usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:492:in `load_missing_constant': Circular dependency detected while autoloading constant RedmineWebhook (RuntimeError)
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
	from /www/redmine/plugins/redmine_webhook/lib/redmine_webhook/projects_helper_patch.rb:2:in `<top (required)>'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /www/redmine/plugins/redmine_webhook/lib/redmine_webhook.rb:1:in `<top (required)>'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:317:in `depend_on'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:233:in `require_dependency'
	from /www/redmine/plugins/redmine_webhook/init.rb:1:in `<top (required)>'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /www/redmine/lib/redmine/plugin.rb:155:in `block in load'
	from /www/redmine/lib/redmine/plugin.rb:146:in `each'
</pre>

**Comment by jegade** [comment]
thank you @suer  - now it works again with redmine 3.0.1.devel
